spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    